apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-app-staging
  namespace: argocd
spec:
  project: devops-training
  source:
    repoURL: https://github.com/Pharosi/devops-app.git
    targetRevision: 11-gitops-argocd
    path: gitops/apps/devops-app/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: devops-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
